### ISSUE TITLE
Create docs

### ISSUE THREAD

**Issue by frmdstryr** [codelv/enaml-native#13]

**Comment by frmdstryr** [comment]
A lot is done, will need updated on an ongoing basis. Closing.

**Comment by frmdstryr** [comment]
![Enaml-native - Creating a android release build](https://user-images.githubusercontent.com/380158/34739803-78127ecc-f54b-11e7-811a-2cef4ba05272.gif)

**Comment by frmdstryr** [comment]
See https://github.com/codelv/enaml-native/blob/master/examples/nav_drawer.enaml
![enaml-native nav-drawer demo](https://user-images.githubusercontent.com/380158/38657098-60a43b9c-3dec-11e8-844b-4ac689417b7c.gif)

**Comment by rodgomesc** [comment]
Thanks.

**Comment by frmdstryr** [comment]
See https://github.com/codelv/enaml-native/blob/master/examples/video_view.enaml
![peek 2018-05-11 18-19](https://user-images.githubusercontent.com/380158/39950787-f3efdeca-5551-11e8-9018-7ab5960c4954.gif)

**Comment by rodgomesc** [comment]
Showw
