### ISSUE TITLE
TypeError: can only concatenate list (not "CommentedSeq") to list

### ISSUE THREAD

**Issue by eolandro** [codelv/enaml-native#68]
Hi
i have been done, this instructions [here](https://www.codelv.com/projects/enaml-native/docs/getting-started), but when i execute **enaml-native run-android** i get **TypeError: can only concatenate list (not "CommentedSeq") to list**
What am i doing wrong?

**Comment by frmdstryr** [comment]
Sounds like a bug.

Which version of the enaml-native-cli is installed? 
Also what version of python? 
Which os? 

Edit: CommandSeq is part of the yaml parser. Was the environment.yaml file modified in any way?

https://stackoverflow.com/questions/30994370/how-can-i-add-a-comment-to-a-yaml-file-in-python

**Comment by eolandro** [comment]
I'm in SparkyLinux 5 (Debian based) and python 3.6
How i know the enaml-native-cli version?

**Comment by frmdstryr** [comment]
Please run `conda list` and `pip list` and paste the output of both here
