### ISSUE TITLE
Transcrypt React Native vs Enaml Native

### ISSUE THREAD

**Issue by kiwi0fruit** [codelv/enaml-native#70]
How do you compare [Transcrypt](https://github.com/QQuick/Transcrypt) + React Native vs Enaml Native? Example of React Native in Transcrypt is [**here**](https://github.com/metamarcdw/Component.py).

**Comment by frmdstryr** [comment]
The example given is for ReactJS, not react native, but assuming transcrypt did also work with RN theres still a major difference in library support.

Enaml native uses cross compiled CPython. Therefore any python libraries, including those with c-extensions, can be used as long as they can also be cross compiled (using conda mobile).

From what I understand, Transcript compiles python code to js and thus will not support using any existing python libraries with c extensions (ex numpy, lxml, crypto...).  

Hope that helps.

**Comment by kiwi0fruit** [comment]
I guess RN example is here: https://github.com/metamarcdw/react-native-transcrypt

I more or less understand the differences:

* startup speed time
* app size
* using python libs vs using js libs (including React Native modules)
* having annoying \_\_pragma\_\_ annotations

Which way you think more vitable or convenient in the future?

**Comment by frmdstryr** [comment]
I think which is more viable/convenient depends on your needs and whether you prefer react or enaml.

Personally, I avoid transpilers (except cython) because of library incompatibilities that often come with.
