### ISSUE TITLE
is it possible to have screen manager like kivy?

### ISSUE THREAD

**Issue by Mohamed-Kaizen** [codelv/enaml-native#71]
I was wondering if it possible to change from one screen to another like kivy screen manager

**Comment by frmdstryr** [comment]
Try the [ViewPager](https://enaml-native.readthedocs.io/en/latest/widgets/viewpager.html)

**Comment by frmdstryr** [comment]
If you want a screen to pop up like a new activity you can use a Dialog and set `style = "@style/ActivityDialog"`. See https://github.com/codelv/enaml-native/blob/master/examples/dialog.enaml#L52

**Comment by Mohamed-Kaizen** [comment]
ok thinks
