### ISSUE TITLE
package into android app

### ISSUE THREAD

**Issue by Brianzhengca** [codelv/enaml-native#73]
hi there i am just wondering if there is a way to package my python code into an android app??? i have a simple hello world program and i am using mac and a windows

**Comment by Brianzhengca** [comment]
how about ios???

**Comment by frmdstryr** [comment]
Could you be more specific?

**Comment by Brianzhengca** [comment]
I just need to package a basic hello world app into android and ios to test both on my phone and my ipad

**Comment by frmdstryr** [comment]
Yes enaml-native will work for Android but iOS is not complete.

If you create an app any python code you put in the src folder will be "packaged" into the app.
