### ISSUE TITLE
Hello World 

### ISSUE THREAD

**Issue by K3nn3th2** [codelv/enaml-native#77]
Hey Folks,

Im trying to run the HelloWorld app on my Android 9 Phone which is created with 
enaml-native create app

using
enaml-native run-android

everything is built (there is an error about the 'zipfile' module but i believe it is irrelevant) fine and it is deployed to my phone but the app crashes on start after displaying the python logo briefly.

how can i proceed to debug this?

**Comment by frmdstryr** [comment]
Run adb logcat then start the app and look for a traceback.  It may also be an issues with more recent versions of android.

**Comment by K3nn3th2** [comment]
thanks for the tip! 
here is what i could find:

08-08 12:36:25.603   687   722 I AssetExtractor: Unpacking took 547 ms
08-08 12:36:25.605   687   722 I pybridge: Initializing the Python interpreter
08-08 12:36:25.605   687   722 I pybridge: /data/user/0/com.example.helloworld/cache
08-08 12:36:25.605   687   722 I pybridge: /data/user/0/com.example.helloworld/assets/python
08-08 12:36:25.605   687   722 I pybridge: /data/app/com.example.helloworld-pVEDvT74VXI-hGwm8C0E_Q==/lib/arm64
08-08 12:36:25.614   687   760 D pybridge: Could not find platform independent libraries <prefix>
08-08 12:36:25.614   687   760 D pybridge: Could not find platform dependent libraries <exec_prefix>
08-08 12:36:25.614   687   760 D pybridge: Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
08-08 12:36:25.624   687   760 D pybridge: Fatal Python error: Py_Initialize: Unable to get the locale encoding
08-08 12:36:25.624   687   760 D pybridge: ImportError: 
08-08 12:36:25.624   687   760 D pybridge: bad magic number in 'encodings': b'\x03\xf3\r\n'
08-08 12:36:25.624   687   760 D pybridge: Current thread 0x
08-08 12:36:25.624   687   760 D pybridge: 0000007e2c99d4f0 (most recent call first):
08-08 12:36:25.638   687   722 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 722 (Thread-2), pid 687 (mple.helloworld)

do you have any ideas how i could continue?

**Comment by frmdstryr** [comment]
It looks like the encodings module of the arm64 build of python is not working.

**Comment by K3nn3th2** [comment]
okay. is there anything that can be done? can we rebuild it or something?

**Comment by frmdstryr** [comment]
This recipe needs fixed/rebuilt https://github.com/codelv/conda-mobile/tree/master/android-python3 

The patches probably need modified more for arm64. Or possibly it's something stupid like it's copying the files for the wrong arch into the arm64 folder. 

Edit: The files all look fine. 

Can you extract the apk and find the lib folder and run `file *.so` to make sure they all say 'ARM aarch64'?

**Comment by frmdstryr** [comment]
I didn't have an arm64 phone to test the builds on at the time.

**Comment by K3nn3th2** [comment]
yep, looks like it.

lib.array.so:                           ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._asyncio.so:                        ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib.atom.catom.so:                      ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib.atom.datastructures.sortedmap.so:   ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib.binascii.so:                        ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._bisect.so:                         ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._blake2.so:                         ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._bz2.so:                            ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
libc++_shared.so:                       ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=756f31c1c7c97699d49116ce0208eb9316d88a73, stripped
lib._csv.so:                            ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._datetime.so:                       ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib.enaml.callableref.so:               ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib.enaml.c_compat.so:                  ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib.enaml.core.alias.so:                ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib.enaml.core.declarative_function.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib.enaml.core.dynamicscope.so:         ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib.enaml.core.funchelper.so:           ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib.enaml.signaling.so:                 ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib.enaml.weakmethod.so:                ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib.fcntl.so:                           ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._hashlib.so:                        ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._heapq.so:                          ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._json.so:                           ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._lsprof.so:                         ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._lzma.so:                           ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib.math.so:                            ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._md5.so:                            ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib.msgpack._packer.so:                 ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib.msgpack._unpacker.so:               ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._multibytecodec.so:                 ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._multiprocessing.so:                ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._opcode.so:                         ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib.parser.so:                          ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._pickle.so:                         ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._posixsubprocess.so:                ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
libpybridge.so:                         ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=7a8c895ced090be0164659ed6a89880f5c11866e, stripped
libpython3.6m.so:                       ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._random.so:                         ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib.resource.so:                        ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib.select.so:                          ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._sha1.so:                           ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._sha256.so:                         ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._sha3.so:                           ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._sha512.so:                         ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._socket.so:                         ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._struct.so:                         ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._testcapi.so:                       ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib.unicodedata.so:                     ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib._weakref.so:                        ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
lib.zlib.so:                            ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped

**Comment by frmdstryr** [comment]
All the conda recipes should be updated to work on python 3.7 at some point anyways.

Kivy is now using 3.7.1 https://github.com/kivy/python-for-android/blob/develop/pythonforandroid/recipes/python3/__init__.py

**Comment by K3nn3th2** [comment]
sorry what do you mean by that, regarding enaml-native on arm64?

**Comment by frmdstryr** [comment]
The recipes currently build python 3.6.5, they should be updated to 3.7.4 and in the process fix any issues with arm64.

**Comment by K3nn3th2** [comment]
so i presume its just a matter of time before i can code with enaml-native for my phone? :)

**Comment by frmdstryr** [comment]
You caught me at a good time :) 

I'll see if I can get 3.7 to build and run on my new phone (arm64), I want to update my one app anyways.

**Comment by K3nn3th2** [comment]
cool! looking forward to progress :) 
I was thinking of making an app for pc and phone. is enaml-native code easy to port to enaml? or are the widgets too different?

**Comment by frmdstryr** [comment]
The widgets are too different (and I don't think you want a phone like app on a desktop anyways), but just about all the models and logic can be the same.

If you can get away with a web app enaml-web works nicely.

**Comment by K3nn3th2** [comment]
i am not quite sure how this would work. can i still use my python functions in the web app?
would it be possible to package the enaml-web app as an android app?

..and did you manage to build 3.7 for arm64? :)

**Comment by frmdstryr** [comment]
Got 3.7.4 and 2.7.16 to build on Monday. Still need to verify they work before uploading them to the repo.  May be some time yet.  I updated the conda-mobile repo if you'd want to try building them and testing out yourself until then.

**Comment by frmdstryr** [comment]
Please update to the latest cli with `pip install --upgrade enaml-native-cli` and create an app. Let me know if you run into any issues, thanks!

**Comment by K3nn3th2** [comment]
Thank you very much!
I had to manually set the execution permmissions for HelloWorld/android/gradlew
but apart from that it works with both python versions 3.7 and 2.7.

Great work!
