### ISSUE TITLE
Python Playground with Examples

### ISSUE THREAD

**Issue by K3nn3th2** [codelv/enaml-native#78]
Hey Folks,

When using python playground with my computer over wifi, some of the example code snippets provided in the left bar work fine, while others (like the ActivityIndicator) yield (type)errors.

am i missing something..?

**Comment by frmdstryr** [comment]
The playground app on the play store is an older version.

**Comment by K3nn3th2** [comment]
That makes sense. Is there an up-to-date version to be found elsewhere?

**Comment by frmdstryr** [comment]
There's no pre-built app but the code is in the examples folder of this repo

**Comment by K3nn3th2** [comment]
will the python playground be re-built with support of the more recent widgets? it would make developing with the web browser work nicely again and would be a speed boost, saving the recompiling every time a minor change is to be tested.

or am i missing a way of doing this another way?

**Comment by frmdstryr** [comment]
You can achieve the same thing as the playground app by running with `dev='server'` as described under the "Server mode" section here: https://codelv.com/projects/enaml-native/docs/debugging

You have to install `pip-tornado` as the builtin event loop doesn't support websockets.
