### ISSUE TITLE
Error while trying ListView Example

### ISSUE THREAD

**Issue by K3nn3th2** [codelv/enaml-native#80]
As stated, i'm having some trouble getting the ListView Example to work.
The App compiles and starts, then i get the following error printed to the phone screen:

Error: Null object reference when updating id=69 method=setTextKeepState

I'm a bit clueless what is causing this error.

thanks for any hints!

**Comment by frmdstryr** [comment]
Let me fix the dev server first :) and I'll see if I get the same error here.

**Comment by frmdstryr** [comment]
Ok, you have to install the enaml-native-icons package then rebuild the app. 

```
# Make sure the channel is there
conda config --add channels codelv 

# Install
enaml-native install enaml-native-icons

# Build again
enaml-native run-android
```

Also the icon's changed, so I need to update the example....  change the "from iconify import material" line with this

```
import iconify
iconify.install() # defaults are material and material_community icons

```

**Comment by K3nn3th2** [comment]
Nice. I had to change "return list(material.ICONS.keys())" to
`        return list(iconify.material.ICONS.keys())
`
and it worked.
Thanks a lot!
