### ISSUE TITLE
Error:  ImportError: bad magic number in 'ply': b'\x03\xf3\r\n'

### ISSUE THREAD

**Issue by null0nil** [codelv/enaml-native#83]
Issue:  
  - Python 3.7 latest pip-ply is packaged with Python2.7 .pyc files:
     -  version 3.11, 
     -  build h62cefb9_1 

A work around is to use build h204e2d7_0:
```
    conda clean -a
    conda uninstall enaml-native
    conda install pip-ply=3.11=h204e2d7_0
    conda install enaml-native
```
Or modify  helloworld/environment.yml from:
```
# App dependencies to be installed
dependencies:
  - python=3.7
  - pip
  - android-python * py37*
  - enaml-native
  - pip:
    - enaml-native-cli
```
to:
```
# App dependencies to be installed
dependencies:
  - python=3.7
  - pip
  - android-python * py37*
  - pip-ply=3.11=h204e2d7_0
  - enaml-native
  - pip:
    - enaml-native-cli
```
And then recreate the conda environment:
```
   conda env remove -n helloworld
   conda env create -f environment.yml 
```

**Comment by frmdstryr** [comment]
Thanks for debugging all these issues. 

I think the best way to solve this would be to build pip-ply with [skip_compile_pyc](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#skip-compiling-some-py-files-into-pyc-files).

**Comment by null0nil** [comment]
Agreed.  That would be the proper way to fix it.   Good to know about it.
