### ISSUE TITLE
"Hook Script Failed" when creating app in mac 10.14.6

### ISSUE THREAD

**Issue by wasimafser** [codelv/enaml-native#84]
OS : Mac OS 10.14.6
PYTHON : 3.7.5

ERROR : https://del.dog/ghutimiwel.txt

File "/opt/miniconda3/lib/python3.7/site-packages/cookiecutter/hooks.py", line 91, in run_script
    'Hook script failed (exit status: {})'.format(exit_status)
cookiecutter.exceptions.FailedHookException: Hook script failed (exit status: 1)

I'm a fresher with this and have no idea on how to progress forward.
Thank you.

**Comment by frmdstryr** [comment]
The script is here https://github.com/codelv/enaml-native-cli/blob/master/enamlnativecli/templates/app/hooks/post_gen_project.py, unfortunately I don't have time to help debug right now. You may be able to edit it in your local install to figure out reason for the error.

**Comment by wasimafser** [comment]
> The script is here https://github.com/codelv/enaml-native-cli/blob/master/enamlnativecli/templates/app/hooks/post_gen_project.py, unfortunately I don't have time to help debug right now. You may be able to edit it in your local install to figure out reason for the error.

Thank you, will try my best and let you know.

**Comment by wasimafser** [comment]
Thank you @frmdstryr , i guess the source isn't updated in Pypi ( particulary with that fix ).
That particaulr fix of lowering the case and removing the spaces is required at most.
