### ISSUE TITLE
'Python.h' file not found

### ISSUE THREAD

**Issue by F1nalFortune** [codelv/enaml-native#85]
Using Xcode Version 11.2.1 (11B500) and MacOS: 10.15.1 (19B88).

<img width="625" alt="Screen Shot 2019-12-26 at 3 14 01 PM" src="https://user-images.githubusercontent.com/13974492/71489140-22f0d980-27f2-11ea-9098-a9e00fbd6643.png">

**Comment by frmdstryr** [comment]
The iOS version is not really complete. The python headers should be copied on build (see https://github.com/codelv/enaml-native-cli/blob/master/enamlnativecli/templates/app/%7B%7Bcookiecutter.project_name%7D%7D/ios/%7B%7Bcookiecutter.project_name%7D%7D.xcodeproj/project.pbxproj#L226) if I remember correctly.
