### ISSUE TITLE
Cookie Error

### ISSUE THREAD

**Issue by kaboomholy** [codelv/enaml-native#86]
every time i attempt to create an app in miniconda with "enaml-native create app" i receive this error
how do i fix this please, and thank you
![cookie error](https://user-images.githubusercontent.com/60334084/73202002-0bf21f80-40ef-11ea-8a90-d8bb252355ad.PNG)
![cookie error 2](https://user-images.githubusercontent.com/60334084/73202017-13192d80-40ef-11ea-9bb9-bccf1d189d96.PNG)

**Comment by frmdstryr** [comment]
The "CondaValueError: prefix already exists" part of the error means conda already has an env using that  name. 

Delete it with `conda envs remove --name <thename>`

**Comment by kaboomholy** [comment]
i deleted the env and re created and got this error

with the cookiecutter
![cookie error 3](https://user-images.githubusercontent.com/60334084/73202978-0695d480-40f1-11ea-9223-1b3bd0fa4fe5.PNG)

**Comment by frmdstryr** [comment]
Looks like something changed on windows.

You need to edit 
https://github.com/codelv/enaml-native-cli/blob/master/enamlnativecli/templates/app/hooks/post_gen_project.py#L26 in your env (ex `C:\users\user\miniconda3\lib\site-packages\enamlnativecli/templates/app/hooks/post_gen_project.py` and change it to:

```python
# -*- coding: utf-8 -*-
import os
import sys
import json
from enamlnativecli.main import find_conda

# Find conda on the system
conda = find_conda()
kw = {}
IS_WIN = 'win' in sys.platform and not 'darwin' == sys.platform 
if IS_WIN:
    process = sys.stdout
else:
    kw['_out_bufsize'] = 0

    def process(c):
        sys.stdout.write(c)
        sys.stdout.flush()

# Create the environment
p = conda('env', 'create', '--file', 'environment.yml',
          _bg=True, _err_to_out=True, _out=process, **kw)
p.wait()

# Find the env
output = conda('env', 'list', '--json')
if IS_WIN:
    data = json.loads(str(output.stdout))
else:
    data = json.loads(str(output))

# Create a symlink from app/venv folder to the conda env
env_name = '{{ cookiecutter.app_name.lower().replace(' ', '') }}'
for path in data['envs']:
    if os.path.split(path)[-1] == env_name:
        os.symlink(path ,'venv')
        break
if not os.path.exists('venv'):
    print("Could not create a link to the env!")
    sys.exit(1)


```

**Comment by kaboomholy** [comment]
ok going to attempt now

**Comment by kaboomholy** [comment]
it returned a different error this time

![cookie error 4](https://user-images.githubusercontent.com/60334084/73205264-87ef6600-40f5-11ea-82ca-c844fb80501e.PNG)

**Comment by frmdstryr** [comment]
Sorry it should be `if sys.version_info.major > 2:` , I edited it above

**Comment by kaboomholy** [comment]
ok attempting againg

**Comment by kaboomholy** [comment]
now this is it
![cookie error 5](https://user-images.githubusercontent.com/60334084/73211583-6300f000-4101-11ea-873a-ac78b48d8ada.PNG)

**Comment by frmdstryr** [comment]
Not sure why it's failing, I updated the code again, can you try that? 

The problem is that [pbs](https://pypi.org/project/pbs/#files) is not outputting a string.

**Comment by kaboomholy** [comment]
can you give me the updated pbs? because i think in my directory i edited mines from aprevious error

**Comment by kaboomholy** [comment]
wait i will try updated code again

**Comment by kaboomholy** [comment]
new error

![cookie error 6](https://user-images.githubusercontent.com/60334084/73217645-2935e680-410d-11ea-8204-9ee16c2a802d.PNG)

**Comment by frmdstryr** [comment]
See https://github.com/explosion/spaCy/issues/895#issuecomment-309054937

> Go to Start->All Programs-> Accessories-> Right click on Command Prompt and select "Run as administrator"

**Comment by kaboomholy** [comment]
ok trying now

**Comment by kaboomholy** [comment]
it worked thanks!!!

and where can i find offcial documentation? i love what i have seen so far

![cookie error 7](https://user-images.githubusercontent.com/60334084/73218798-86329c00-410f-11ea-8dfd-de0f20be2ce0.PNG)

**Comment by kaboomholy** [comment]
or do you have any open source download projects?
