### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by kaboomholy** [codelv/enaml-native#88]
is this file missing?

![no file or directory](https://user-images.githubusercontent.com/60334084/73408134-10196b00-42b0-11ea-9651-df97b84ecf76.PNG)

**Comment by frmdstryr** [comment]
That file is used for optional plugins. It should check if it exists before trying to load it.

See
https://github.com/codelv/enaml-native/blob/76128827c5fd62f2e52bc1ff0955052440acfc52/src/enamlnative/core/app.py#L108

**Comment by kaboomholy** [comment]
i coppied that code to my file and still got the same message

**Comment by frmdstryr** [comment]
Just ignore the error message. If the file is missing (as is normal) it will not load any plugins.

**Comment by kaboomholy** [comment]
ok, thanks i have only created my app , i have not added any code to it yet. is there supposed to be a emulator screen that opens up or how do i get an emulator to show on screen? you have any sugggestions or any links to this? also how do i get android studio to color code my syntax for enaml files?

**Comment by frmdstryr** [comment]
Have you read the docs? 

https://codelv.com/projects/enaml-native/docs/getting-started

You can install the support for python into android studio to get highlighting.

**Comment by kaboomholy** [comment]
i used the scrcpy is there extra steps i need to do to make it pop up on my device?

![miniconda](https://user-images.githubusercontent.com/60334084/73511973-9d39ee00-439c-11ea-8830-268917c459f3.PNG)
