### ISSUE TITLE
APP  on launch

### ISSUE THREAD

**Issue by kaboomholy** [codelv/enaml-native#89]
when i run the enaml code on python plaground it works but when i compile it to apk it just keeps crashing, any ideas why?

it wouldnt allow me to make an apk for the longest until i chaned the styles.xml
and the activity_main.XML

i deleted all the theme settings in the style.xml and in activity main i changed 
xmlns:app="http://schemas.android.com/apk/lib/Entries"

![Screenshot_20200210-214934_Samsung Experience Home (1)](https://user-images.githubusercontent.com/60334084/74296806-c1c98a80-4cf9-11ea-8106-70193bb9ef10.jpg)

![STYLES XML](https://user-images.githubusercontent.com/60334084/74297059-89767c00-4cfa-11ea-978d-50fc932c3174.PNG)

![ACTVITY_MAIN](https://user-images.githubusercontent.com/60334084/74297072-8ed3c680-4cfa-11ea-888c-6e4271ee3ef7.PNG)

**Comment by frmdstryr** [comment]
Please run logcat and capture the log. The playground app is running a very old version of enaml-native.

**Comment by kaboomholy** [comment]
logcat? whats that

**Comment by kaboomholy** [comment]
and this is what happened when i tried to build with the styles file already in the preinstalled package

![styles xml 2](https://user-images.githubusercontent.com/60334084/74298188-dc056780-4cfd-11ea-8824-629abf9b28d4.PNG)
