### ISSUE TITLE
EMPTY APK

### ISSUE THREAD

**Issue by kaboomholy** [codelv/enaml-native#90]
everytime i build an apk the apk is empty with no python or enaml files how do i fix? thanks in advance

![APK NO PYTHON](https://user-images.githubusercontent.com/60334084/74413577-8495f300-4df4-11ea-987d-679705a49907.PNG)

**Comment by kaboomholy** [comment]
I CHANGED somethings and got this

![dex error](https://user-images.githubusercontent.com/60334084/74427468-06dde180-4e0c-11ea-948c-339b9a42e1f3.PNG)

**Comment by frmdstryr** [comment]
Can you please attach the `android/app/build.gradle` and `android/settings.gradle`?  

Gradle should create a bundle of everything named `python.tar.gz` in `android/app/src/main/assets/python`.

**Comment by kaboomholy** [comment]
![build gradle](https://user-images.githubusercontent.com/60334084/74596401-9994a100-5003-11ea-9170-2dd21ccd95c2.PNG)
![settings gradle](https://user-images.githubusercontent.com/60334084/74596405-9e595500-5003-11ea-9799-dcd3b2b477e0.PNG)
