### ISSUE TITLE
implementation doubts

### ISSUE THREAD

**Issue by rodgomesc** [codelv/enaml-native#91]
hello old friend, i don't know if you remember but about 3 years ago i passed by here very excited about this project, i am still in fact, but due to some changes in my life i didn't have much time to collaborate with open source, today mobile development is my main source of income and, I believe that venturing into this project motivated me for this to happen, thanks for that.

today I bring some doubts
currently ...

is there any way to implement linear gradient?

is there any shadow implementation for widgets? if so, would it be possible to implement neumorphic shadows?

in general what are the limitations of this project today.

**Comment by frmdstryr** [comment]
Hey good to hear from you, hope you're doing well. 

You can create and set styles how you do with regular android. Idk how far that'll get.

With that said, I've pretty much stopped doing app/mobile development so unless someone wants to continue it or fund some development. I'd recommend just using regular android.

**Comment by frmdstryr** [comment]
2 years later and nobody still cares :)

**Comment by rodgomescrn** [comment]
you have plans to continue working on this project?

**Comment by frmdstryr** [comment]
Not sure, it didn't take much to update things and get it going again.

**Comment by rodgomesc** [comment]
hey @frmdstryr  the power of python on mobile with c++ libraries is fantastic but when it comes to building  interfaces I feel stuck for building highly customizable interfaces, it's not very customizable, did you ever saw any good alternative to enaml?

**Comment by frmdstryr** [comment]
Jetpack compose works fine for android.
