### ISSUE TITLE
listview example gives ImportError

### ISSUE THREAD

**Issue by Julian-O** [codelv/enaml-native#92]
The file `examples/list_view.enaml` contains the line:

    from atom.api import Atom, Unicode, List, Bool
    
However, the `Unicode` definition [has been removed](https://github.com/nucleic/atom/commit/a8100968157e8ee9b92f9906bc7e65440f91e356) from `atom.api` after being deprecated, so this code no longer runs.

I *think* it needs to be replaced with `Str`. 

This may be a wider issue than this one file.

**Comment by frmdstryr** [comment]
Yeah the whole project needs a find and replace of Unicode with Str

**Comment by frmdstryr** [comment]
Done
